namespace Nutshell.Automation.DaHeng.Sdk
{
	public enum ErrorCode
	{
		CG_OK = 0,
		CG_ALLOCATE_DEVICE_MEMORY_ERROR = -1,
		CG_LOCK_DEVICE_MEMORY_ERROR = -2,
		CG_ACCESS_DEVICE_MEMORY_DENIED = -3,
		CG_PARAMETER_INVALID = -4,
		CG_NOT_SUPPORT_INTERFACE = -5,
		CG_OPEN_DRIVER_FAILED = -6,
		CG_CARD_HANDLE_INVALID = -7,
		CG_NO_CARD_FOUND = -8,
		CG_HW_MAP_MEMORY_ERROR = -9,
		CG_NOT_ENOUGH_SYSTEM_MEMORY = -10,
		CG_HW_INIT_ERROR = -11,
		CG_PARAMETER_OUT_OF_BOUND = -12,
		CG_HW_INIT_I2C_ERROR = -13,
		CG_HW_INIT_AD_ERROR = -14,
		CG_HW_BOARD_TYPE_ERROR = -15,
		CG_SNAP_SHOT_TIME_OUT = -16,
		CG_INIT_DDRAW_ERROR = -17,
		CG_IN_WORK = -18,
		CG_NOT_START_CAPTURE = -19,
		CG_NOT_START_CAPTURE_EX = -20,
		CG_NOT_START_SNAP = -21,
		CG_NOT_START_SNAP_EX = -22,
		CG_NOT_OPEN_SNAP_EX = -23,
		CG_VIDEO_FORMAT_INVALID = -24,
		CG_NOT_SUPPORT_CARD_TYPE = -25,
		CG_FILE_CREATE_ERROR = -26,
		CG_FILE_INVALID = -27,
		CG_VGA_BASE_INVALID = -28,
		CG_VIDEO_WINDOW_INVALID = -29,
		CG_INTERNAL_ERROR = -30
	}
}